Veewee::Session.declare({
  :cpu_count => '1',
  :memory_size=> '512',
  :disk_size => '40000',
  :disk_format => 'VDI',
  :hostiocache => 'off',
  :os_type_id => 'Debian',
  :iso_file => "kali-linux-1.0.5-i386.iso",
  :iso_src => "http://cdimage.kali.org/kali-images/kali-1.0.5/kali-linux-1.0.5-amd64.iso",
  :iso_md5 => '832e141a16a961fac26d8177cb99f0fa',
  :iso_download_timeout => "1000",
  :boot_wait => "10",
  :boot_cmd_sequence => [
    '<Esc>',
    'install ',
    'url=http://%IP%:%PORT%/preseed.cfg ',
    'noconfig=sudo ',
    'username=root ',
    'locale=en_US.UTF-8 ',
    'kbd=us ',
    'keymap=us ',
    'hostname=%NAME% ',
    'domain=vagrantup.com ',
    'auto=true ',
    'noprompt ',
    'priority=critical ',
    'debconf/frontend=noninteractive ',
    'console-setup/ask_detect=false ',
    'console-keymaps-at/keymap=us ',
    '<Enter>'
  ],
  :kickstart_port => "7122",
  :kickstart_timeout => "10000",
  :kickstart_file => "preseed.cfg",
  :ssh_login_timeout => "10000",
  :ssh_user => "vagrant",
  :ssh_password => "vagrant",
  :ssh_key => "",
  :ssh_host_port => "7222",
  :ssh_guest_port => "22",
  :sudo_cmd => "echo '%p'|sudo -S sh '%f'",
  :shutdown_cmd => "shutdown -P now",
  :postinstall_files => [ "postinstall.sh"],
  :postinstall_timeout => "10000"
})
